### PR TITLE
checker/badCond: rhs should be also check for safe expr

### LINKED ISSUE #1485: badCond: reports wrong suspicious condition
Found a bug in `badCond`: 

```
if paramType == lastParam.GetType() && paramType == bgp.BGP_ASPATH_ATTR_TYPE_SEQ {
```

Which indeed looks suspicious but here is the thing: `GetType()` might return `BGP_ASPATH_ATTR_TYPE_SEQ` which is a correct behaviour.

I think in `badCond` we should compare only simple/pure/safe expressions.

### PR DESCRIPTION
**Pull request by codeimmortal**
Added checks for RHS also, in case of unsafe expression we should not throw errors.

@cristaloleg 

Fixes #1485

### CODE REVIEW

File: checkers/badCond_checker.go [hunk 1]
```diff
@@ -86,8 +87,20 @@ func (c *badCondChecker) checkExpr(expr ast.Expr) {
 }
 
 func (c *badCondChecker) equalToBoth(lhs, rhs *ast.BinaryExpr) bool {
-	return lhs.Op == token.EQL && rhs.Op == token.EQL &&
-		astequal.Expr(lhs.X, rhs.X)
```
Comment (cristaloleg) [inline checkers/badCond_checker.go:90]: Hm, feels like 
```
return lhs.Op == token.EQL && rhs.Op == token.EQL &&
		astequal.Expr(lhs.X, rhs.X) &&
        typep.SideEffectFree(info, rhs.X)
```

is what we need, isn't it?

Comment (codeimmortal) [reply checkers/badCond_checker.go:90]: Yes this approach will also solve it. Shall we check both Y value for both sideEffectFree. That will be perfect. I think typep.SideEffectFree(info, rhs.X) was mistake, you want rhs.Y to be validated.

func (c *badCondChecker) equalToBoth(lhs, rhs *ast.BinaryExpr) bool {
	return lhs.Op == token.EQL && rhs.Op == token.EQL &&
		astequal.Expr(lhs.X, rhs.X) &&
		typep.SideEffectFree(c.ctx.TypesInfo, lhs.Y) && typep.SideEffectFree(c.ctx.TypesInfo, rhs.Y)
}

Comment (cristaloleg) [reply checkers/badCond_checker.go:90]: Yeah, I might be wrong with the real expression but looks like everything can be done in a few additional lines if I'm not mistaken.

Comment (codeimmortal) [reply checkers/badCond_checker.go:90]: Added condition. Thanks for suggestion. Now it is clean.

**Review by quasilyte — APPROVED** [review]

**Review by cristaloleg — APPROVED** [review]
