### PR TITLE
checkers: fix panic in flagName

### LINKED ISSUE #734: checkers: flagName panics
Panic (index-out-of-bounds) hapens on line 36:
```go
c.checkFlagName(call, call.Args[0])
```
It's a mystery how either of these funcs can have 0 args:
```
"flag.Bool", "flag.Duration", "flag.Float64", "flag.String",
		"flag.Int", "flag.Int64", "flag.Uint", "flag.Uint64"
```
Needs investigation (and a fix).

```
flagName: error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 5110 [running]:
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).checkFile.func1.1(0xc00df739e0, 0xc017c3a780)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:136 +0x15b
panic(0x810d20, 0xcbc9e0)
	$GOROOT/src/runtime/panic.go:513 +0x1b7
github.com/go-critic/go-critic/checkers.(*flagNameChecker).VisitExpr(0xc0176c35f0, 0x8cda60, 0xc00a6b55c0)
	$GOPATH/src/github.com/go-critic/go-critic/checkers/flagName_checker.go:36 +0x680
github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile.func1(0x8c8860, 0xc00a6b55c0, 0xc00657ed01)
	$GOPATH/src/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:23 +0x7f
go/ast.inspector.Visit(0xc00afd8750, 0x8c8860, 0xc00a6b55c0, 0x8c7a20, 0xc00afd8750)
	$GOROOT/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c8860, 0xc00a6b55c0)
	$GOROOT/src/go/ast/walk.go:52 +0x66
go/ast.walkExprList(0x8c7a20, 0xc00afd8750, 0xc00657edb0, 0x1, 0x1)
	$GOROOT/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c8660, 0xc00a6b5600)
	$GOROOT/src/go/ast/walk.go:207 +0x2103
go/ast.walkStmtList(0x8c7a20, 0xc00afd8750, 0xc00a6b5700, 0x3, 0x4)
	$GOROOT/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c87e0, 0xc00a6b0d20)
	$GOROOT/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c9060, 0xc00a68b810)
	$GOROOT/src/go/ast/walk.go:285 +0x2961
go/ast.walkStmtList(0x8c7a20, 0xc00afd8750, 0xc00657eed0, 0x1, 0x1)
	$GOROOT/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c87e0, 0xc00a6b0d50)
	$GOROOT/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x8c7a20, 0xc00afd8750, 0x8c8c60, 0xc00a6b0d80)
	$GOROOT/src/go/ast/walk.go:344 +0xd73
go/ast.Inspect(...)
	$GOROOT/src/go/ast/walk.go:385
github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile(0xc0176c3600, 0xc0022a8680)
	$GOPATH/src/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:21 +0x12c
github.com/go-lintpack/lintpack.(*Checker).Check(...)
	$GOPATH/src/github.com/go-lintpack/lintpack/lintpack.go:126
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).checkFile.func1(0xc00df739e0, 0xc0022a8680, 0xc00afef720, 0x1, 0x1, 0x0, 0xc017c3a780)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:144 +0x98
created by github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).checkFile
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:126 +0x120
```

### PR DESCRIPTION
**Pull request by Quasilyte**
Verify that "flag.Xxx" function comes from the standard
library, not from just any package that is called flag and
happen to have something like Bool or Int8 function that
look like something from the standard flag package.

Move stdlib pkg check to utils.go and use that in
importShadow checker as well.

Fixes #734

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

### CODE REVIEW

File: checkers/utils.go [hunk 1]
```diff
@@ -8,6 +8,11 @@ import (
 	"github.com/go-lintpack/lintpack"
 )
 
+// isStdlibPkg reports whether pkg is a package from the Go standard library.
+func isStdlibPkg(pkg *types.Package) bool {
```
Comment (cristaloleg) [inline checkers/utils.go]: Good one
