### PR TITLE
checkers: refactor and fix hexLiteral checker

### LINKED ISSUE #780: hexLiterals: false positives on hex lits without letters
Reproducer: any hex literal without letter digits after `0x`.
Examples:
```go
0x30
0x11
0x1130243
```
Negative tests suite should be extended.

### PR DESCRIPTION
**Pull request by Quasilyte**
Also renamed it from hexLiterals to hexLiteral.

Fixes #780

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

### CODE REVIEW

File: checkers/testdata/hexLiteral/negative_tests.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+func noLetters() {
+	_ = 0x11
+	_ = 0x0
+}
+
+func digitsAndLetters() {
+	_ = 0x1aa
+	_ = 0x1AA
+}
```
Comment (cristaloleg) [inline checkers/testdata/hexLiteral/negative_tests.go]:
```suggestion
}

func decimals() {
	_ = 1
	_ = 10
	_ = 12345
}
```
