### PR TITLE
checkers: ignore `defer exit()` in exitAfterDefer

### LINKED ISSUE #995: exitAfterDefer: false positive
exitAfterDefer seems to give a false positive with this code:

```
package main

import (
	"fmt"
	"io"
	"os"
)

func main() {
	items, err := process()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n\n", err)
		defer os.Exit(1)
	} else {
		defer os.Exit(0)
	}

	fmt.Println("output", items)
}

func process() ([]int, error) { return []int{1, 2, 3}, io.EOF }
```

Output:
```
example> gocritic check .
./main.go:15:9: exitAfterDefer: os.Exit clutters `defer os.Exit(1)`
```

### PR DESCRIPTION
**Pull request by quasilyte**
We allow `defer os.Exit()` calls
as it's harder to determine whether they're going
to clutter anything without actually trying to
simulate the defer stack + understanding the control flow.

Fixes #995

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]

File: checkers/exitAfterDefer_checker.go [hunk 1]
```diff
@@ -52,7 +52,18 @@ func (c *exitAfterDeferChecker) VisitFuncDecl(fn *ast.FuncDecl) {
...
+			// to clutter anything without actually trying to
+			// simulate the defer stack + understanding the control flow.
+			// TODO: can we use CFG here?
+			if _, ok := cur.Parent().(*ast.DeferStmt); ok {
+				return true
+			}
 			if deferStmt != nil {
+				if deferStmt.Call == n {
+					return true
+				}
```
Comment (quasilyte) [inline checkers/exitAfterDefer_checker.go:66]: This check (`deferStmt.Call == n`) is redundant.
